added rejection of X_i with V_i mingling - updated tests to test compilation failure easily

diff --git a/test b/test
--- a/test
+++ b/test
@@ -9,6 +9,7 @@
 
 Testfold="tests"
 Iterfold="interoperation"
+Failfold="fails"
 Logfold="log"
 Compiler=./compile
 Linker=./link
@@ -23,13 +24,24 @@ function newlog
     echo "$newlog"
 }
 
-#==== printr : print succes or failure  ====
-function printr
+#==== logtest : log what happens for test $2 ====
+function logtest
+{
+    echo "" >> $1
+    echo "" >> $1
+    echo "#==========================================#" >> $1
+    echo "# Result for $2" >> $1
+    echo "#==========================================#" >> $1
+    echo "" >> $1
+}
+
+#==== printr : print succes or failure ====
+function printr 
 {
     if [[ $# -lt 0 ]];then
         exit 1;
     else
-        if [[ $1 -ne 0 ]];then
+        if [[ $1 -ne $2 ]];then
             echo -e "\033[1;31m[FAIL]\033[0m"
         else 
             echo -e "\033[1;33m[PASS]\033[0m"
@@ -38,29 +50,27 @@ function printr
 }
 
 
-#==== toplevel ====
+# Make Log
 logname=$(newlog)
 echo "== All output stored in: $logname =="
 echo "== $logname ==" >>$logname
 
+#==== Normal Tests ====
+echo ">> Normal Tests <<"
+echo ">> Normal Tests <<" >> $logname
 for file in ${Testfold}/*.ml
 do
     tabs 4
     name=${file##*/}
     base=${name%.ml}
-    echo "" >> $logname
-    echo "" >> $logname
-    echo "#==========================================#" >> $logname
-    echo "# Result for $base" >> $logname
-    echo "#==========================================#" >> $logname
-    echo "" >> $logname
-    echo "Testing :: $base"
+    logtest $logname $base
+    echo "Testing :: $2"
 
     # test compilation and abort further tests if failed
     echo -ne "\tCompilation :: "
     $Compiler $file >> $logname 2>&1
     res=$?
-    printr $res
+    printr $res 0
     tabs 8
     case $res in
         
@@ -78,7 +88,6 @@ do
     esac
     tabs 4
 
-    
     # the specific interoperation tests for this file
     for testf in ${Testfold}/${Iterfold}/*.c
     do
@@ -93,7 +102,7 @@ do
             echo -ne "\tLinking :: "
             $Linker ${Outfold}/${base}.o ${testf} >> $logname 2>&1
             res=$?
-            printr $res
+            printr $res 0
             if [[ $res -ne 0 ]];then
                 echo -ne "\t--> "
                 if [[ $res -ne 2 ]];then
@@ -105,9 +114,25 @@ do
             # The actual test
             echo -ne "\tExecution :: "
             ./${Outfold}/${base}.bin >> $logname 2>&1 
-            printr $? 
+            printr $? 0
         fi
     done
+done
+
+#==== Failure Tests ====
+echo -e "\n>> Failure Tests <<"
+echo ">> Failure Tests <<" >> $logname
+for file in ${Testfold}/${Failfold}/*.ml
+do
+    testname=${file##*/}
+    logtest $logname $testname
+    echo "Testing for :: $testname"
+    code=$(perl -pe "m/ERRORCODE (?<num>\d+)/; print $+{num}; exit" $file) # I don't understan perl -ne
+    echo -ne "\tCompilation :: "
+    $Compiler $file >> $logname 2>&1
+    res=$?
+    printr $res $code  
+     
 done
 
 exit 0
